services:
  - type: web
    name: proofly-api
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: proofly-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: API_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: ALLOWED_ORIGINS
        value: https://yourdomain.com,https://www.yourdomain.com
      - key: RATE_LIMIT_PER_MINUTE
        value: 60

databases:
  - name: proofly-db
    databaseName: proofly
    user: proofly
    plan: free 